/* empty css                      */import{a as w,S as P,i as n}from"./assets/vendor-B4VFN8au.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v="53603098-b02aa90545e6d43ec2b5cc7bc",E="https://pixabay.com/api/";async function g(t,o=1){const s={key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:o};try{return(await w.get(E,{params:s})).data}catch(i){throw console.error("API Error:",i),i}}function p(t){return t.map(({webformatURL:o,largeImageURL:s,tags:i,likes:e,views:r,comments:c,downloads:L})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${o}" alt="${i}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b>${e}</p>
          <p class="info-item"><b>Views</b>${r}</p>
          <p class="info-item"><b>Comments</b>${c}</p>
          <p class="info-item"><b>Downloads</b>${L}</p>
        </div>
      </li>`).join("")}function S(t){t.innerHTML=""}const q=document.querySelector(".search-form"),d=document.querySelector(".gallery"),h=document.querySelector(".loader"),a=document.querySelector(".load-more");let u="",l=1,f=0;const $=15;let y=new P(".gallery a",{captionsData:"alt",captionDelay:250});a.classList.add("is-hidden");q.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.query.value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}u=o,l=1,S(d),a.classList.add("is-hidden"),b();try{const s=await g(u,l);if(s.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"}),m();return}f=Math.ceil(s.totalHits/$);const i=p(s.hits);d.innerHTML=i,y.refresh(),n.success({title:"Success",message:`Hooray! We found ${s.totalHits} images.`,position:"topRight"}),f>1&&a.classList.remove("is-hidden")}catch{n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{m()}});a.addEventListener("click",async()=>{l+=1,b(),a.classList.add("is-hidden");try{const t=await g(u,l),o=p(t.hits);d.insertAdjacentHTML("beforeend",o),y.refresh(),H(),l>=f?(a.classList.add("is-hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):a.classList.remove("is-hidden")}catch{n.error({title:"Error",message:"Error fetching more images."})}finally{m()}});function b(){h.style.display="block"}function m(){h.style.display="none"}function H(){const{height:t}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
