/* empty css                      */import{a as S,S as q,i as n}from"./assets/vendor-2TIoixgK.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const v="53603098-b02aa90545e6d43ec2b5cc7bc",E="https://pixabay.com/api/";async function h(e,r=1){const o={key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r};try{return(await S.get(E,{params:o})).data}catch(i){throw console.error("API Error:",i),i}}let g;function M(e){return e.map(({webformatURL:r,largeImageURL:o,tags:i,likes:t,views:s,comments:c,downloads:P})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${r}" alt="${i}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b>${t}</p>
          <p class="info-item"><b>Views</b>${s}</p>
          <p class="info-item"><b>Comments</b>${c}</p>
          <p class="info-item"><b>Downloads</b>${P}</p>
        </div>
      </li>`).join("")}function b(e,r,o=!1){const i=M(e);o?r.insertAdjacentHTML("beforeend",i):r.innerHTML=i,g?g.refresh():g=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function $(e){e.innerHTML=""}function L(e){e.style.display="block"}function m(e){e.style.display="none"}function w(e){e.classList.remove("is-hidden")}function u(e){e.classList.add("is-hidden")}const H=document.querySelector(".form"),d=document.querySelector(".gallery"),l=document.querySelector(".loader"),a=document.querySelector(".load-more");let p="",f=1,y=0;const O=15;u(a);H.addEventListener("submit",async e=>{e.preventDefault();const r=e.target.elements.query.value.trim();if(!r){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}p=r,f=1,$(d),u(a),L(l);try{const o=await h(p,f);if(o.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"}),m(l);return}y=Math.ceil(o.totalHits/O),b(o.hits,d,!1),n.success({title:"Success",message:`Hooray! We found ${o.totalHits} images.`,position:"topRight"}),y>1&&w(a)}catch(o){console.log(o),n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{m(l)}});a.addEventListener("click",async()=>{f+=1,u(a),L(l);try{const e=await h(p,f);b(e.hits,d,!0),R(),f>=y?(u(a),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w(a)}catch{n.error({title:"Error",message:"Error fetching more images."})}finally{m(l)}});function R(){const e=d.querySelector(".gallery-item");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
