/* empty css                      */import{a as v,S as q,i as n}from"./assets/vendor-2TIoixgK.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const E="53603098-b02aa90545e6d43ec2b5cc7bc",$="https://pixabay.com/api/";async function p(t,r=1){const s={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r};try{return(await v.get($,{params:s})).data}catch(i){throw console.error("API Error:",i),i}}let f;function h(t,r,s=!1){const i=t.map(({webformatURL:e,largeImageURL:o,tags:l,likes:L,views:w,comments:P,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${e}" alt="${l}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b>${L}</p>
          <p class="info-item"><b>Views</b>${w}</p>
          <p class="info-item"><b>Comments</b>${P}</p>
          <p class="info-item"><b>Downloads</b>${S}</p>
        </div>
      </li>`).join("");s?r.insertAdjacentHTML("beforeend",i):r.innerHTML=i,f?f.refresh():f=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function H(t){t.innerHTML=""}const I=document.querySelector(".form"),d=document.querySelector(".gallery"),y=document.querySelector(".loader"),a=document.querySelector(".load-more");let u="",c=1,m=0;const M=15;a.classList.add("is-hidden");I.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.elements.query.value.trim();if(!r){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}u=r,c=1,H(d),a.classList.add("is-hidden"),b();try{const s=await p(u,c);if(s.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"}),g();return}m=Math.ceil(s.totalHits/M),h(s.hits,d),n.success({title:"Success",message:`Hooray! We found ${s.totalHits} images.`,position:"topRight"}),m>1&&a.classList.remove("is-hidden")}catch(s){console.log(s),n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{g()}});a.addEventListener("click",async()=>{c+=1,b(),a.classList.add("is-hidden");try{const t=await p(u,c);h(t.hits,d,!0),O(),c>=m?(a.classList.add("is-hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):a.classList.remove("is-hidden")}catch{n.error({title:"Error",message:"Error fetching more images."})}finally{g()}});function b(){y.style.display="block"}function g(){y.style.display="none"}function O(){const t=d.querySelector(".gallery-item");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
